config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :recipes do
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy 
    #ttachment :image
    has_one_attached :photo
    with_options presence: true do
        validates :title
        validates :artist
        validates :body
        #validates :bpm
        validates :Genre
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #attachment :profile_image
  has_one_attached :image
  has_many :recipes, dependent: :destroy
  has_many :comments
  
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
     @comment = current_user.comments.new(comment_params)
     if @comment.save
         redirect_back(fallback_location: root_path) 
     else
       redirect_back(fallback_location: root_path)  #同上
     end
    end
    
    private
    def comment_params
      params.require(:comment).permit(:comment_content, :recipe_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @recipes = Recipe.all.order(id: "DESC")
  end

  def show
    @recipe = Recipe.find(params[:id])
    @comments = @recipe.comments
    @comment = current_user.comments.new
    @user = @comment.user
  end

  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipe_path(@recipe), notice: '投稿に成功しました。'
    else
      render :new
    end
  end
  
  def edit
    @recipe = Recipe.find(params[:id])
    if @recipe.user != current_user
      redirect_to recipes_path, alert: '不正なアクセスです'
    end
  end
  
  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipes_path
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: '更新に成功しました。'
    else
      render :edit
    end
  end
  private
  def recipe_params
    params.require(:recipe).permit(:title, :body, :bpm, :bestsong, :Genre, :photo, :artist)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: '不正なアクセスです'
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user),  notice: '更新に成功しました。'
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image, :image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="titledonut">DONUT</strong>
        </p>
      </div>
      <div class="container">
        <div class="columns is-centered">
          <div class="column is-10">
            <div class="sp-image-wrap">
              <figure>
                <div class="main-image is-centered"></div>
              </figure>
              <span class="sp-description">
              <br>
              <%= link_to "ログイン", new_user_session_path, class: "button is-black is-fullwidth" %>
              <br>
              <%= link_to "新規登録", new_user_registration_path, class: "button is-black is-fullwidth" %>
              </span>
    　　　  　</div>
          </div>
        </div>
      </div>
    </div>
  </article>
  <br>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DONUT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-black p-5">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="bartitle">DONUT</h1>
        <% end %>
      </div>
      
      <% if user_signed_in? %>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <%= link_to recipes_path, class: "navbar-item" do %>
              <h1 class="baritem">レコード一覧</h1>
              <% end %>
              <%= link_to new_recipe_path, class: "navbar-item" do %>
                <h1 class="baritem">レコード投稿</h1>
              <% end %>
              <%= link_to users_path, class: "navbar-item" do %>
                <h1 class="baritem">DONUT会員一覧</h1>
              <% end %>
              <%= link_to user_path(current_user), class: "navbar-item" do %>
                <h1 class="baritem">マイページ</h1>
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "navbar-item" do %>
                <h1 class="baritem">ログアウト</h1>
              <% end %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <%= link_to recipes_path, class: "navbar-item" do %>
                <h1 class="baritem">レコード一覧</h1>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
 <section class="hero is-dark is-small">
  <div class="hero-body">
    <div class="container">
      <h1 class="title is-size-6">
        レコード編集
      </h1>
    </div>
  </div>
</section>

<% if @recipe.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@recipe.errors.count, "error") %> 発生しました。</h2>
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @recipe do |f| %>
          <div class="field">
            <%= f.label :title, "Title", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :artist, "Artist", class: "label" %>
            <%= f.text_field :artist, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :body, "Description", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>
          
          <div class="field">
            <%= f.label :bestsong, "Bestsong", class: "label" %>
            <%= f.text_field :bestsong, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :bpm, "BPM", class: "label" %>
            <%= f.text_field :bpm, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :Genre, "Genre", class: "label" %>
            <%= f.select :Genre, {'Soul': 1,'Funk': 2,'Dance': 3,'R&B': 4,'Citypop': 5,'Hiphop': 6,'Reggae': 7,'Jazz': 8,'Rock': 9,'Other': 10}, {include_blank: '選択してください'}, { class: 'input' , required: true }%>
          </div>
          

          <div class="field">
            <%= f.label :image, "Record Jacket", class: "label" %>
            <%= f.file_field :photo %><br>
          </div>

            <%= f.submit "投稿", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/index.html.erb
<section class="hero is-dark is-small">
  <div class="hero-body">
    <div class="container">
      <h1 class="title is-size-6">
        レコード一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @recipes.each do |recipe| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to recipe_path(recipe) do %>
                  <% if recipe.photo.attached? %>
                    <%= image_tag recipe.photo %>
                  <% end %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%#<%= attachment_image_tag recipe.user, :profile_image, fallback: "no-image/" %>
                    <% if recipe.user.image.attached? %>
                      <%= image_tag recipe.user.image %>
                    <% end %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%= link_to recipe.title, recipe_path(recipe) %></div>
                </div>
              </div>

              <div class="content">
                <time>
                  <%= recipe.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/recipes/new.html.erb
 <section class="hero is-dark is-small">
  <div class="hero-body">
    <div class="container">
      <h1 class="title is-size-6">
        今日もレコード掘った？
      </h1>
    </div>
  </div>
</section>

<% if @recipe.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
        <%= form_for @recipe do |f| %>
          <div class="field">
            <%= f.label :title, "Title", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :artist, "Artist", class: "label" %>
            <%= f.text_field :artist, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :body, "Description", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>
          
          <div class="field">
            <%= f.label :Genre, "Genre", class: "label" %>
            <%= f.select :Genre, {'Soul': 1,'Funk': 2,'Dance': 3,'R&B': 4,'Citypop': 5,'Hiphop': 6,'Reggae': 7,'Jazz': 8,'Rock': 9,'Other': 10}, {include_blank: '選択してください'}, { class: 'input' , required: true }%>
          </div>
          
          <div class="field">
            <%= f.label :bestsong, "Bestsong", class: "label" %>
            <%= f.text_field :bestsong, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :bpm, "Bestsong BPM", class: "label" %>
            <%= f.text_field :bpm, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :image, "Record Jacket", class: "label" %>
            <%#<%= f.file_field :image, class: "input" %>
            <%= f.file_field :photo %><br>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/show.html.erb
<section class="hero is-dark is-small">
  <div class="hero-body">
    <div class="container">
      <h1 class="title is-size-6">
        レコード詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
          　<% if @recipe.photo.attached? %>
              <%= image_tag @recipe.photo %>
            <% end %>
          </div>
          <div class="card-content">
            <div class="content">
                <p class="title is-4"><%= @recipe.title %></p>
                <p class="title is-6"><%= @recipe.artist %></p>
              <table class="table is-narrow">
                <tr>
                  <th>説明</th>
                </tr>
                <tr>
                  <td><%= simple_format @recipe.body %></td>
                </tr>
                <tr>
                　<th>Bestsong</th>
                </tr>
                <tr>
                  <td><%= simple_format @recipe.bestsong %></td>
                </tr>
                <tr>
                　<th>Bestsong BPM</th>
                </tr>
                <tr>
                  <td><%= simple_format @recipe.bpm %></td>
                </tr>
                <tr>
                　<th>Genre</th>
                </tr>
                <tr>
                  <% if @recipe.Genre == "1" %>
                　   <td>Soul</td>  
                　<% elsif @recipe.Genre == "2" %>
                　   <td>Funk</td>  
                　<% elsif @recipe.Genre == "3" %>
                　   <td>Dub</td>  
                　<% elsif @recipe.Genre == "4" %>
                　   <td>R&B</td>  
                　<% elsif @recipe.Genre == "5" %>
                　   <td>Citypop</td> 
                　<% elsif @recipe.Genre == "6" %>
                　   <td>Hiphop</td>
                　<% elsif @recipe.Genre == "7" %>
                　   <td>Reggae</td>
                　<% elsif @recipe.Genre == "8" %>
                　   <td>Jazz</td>
                　<% elsif @recipe.Genre == "9" %>
                　   <td>Rock</td>
                　<% elsif @recipe.Genre == "10" %>
                　   <td>Other</td>
                　<% end %>
                </tr>
              </table>
              <% if @recipe.user.id == current_user.id %>
                <%= link_to "編集", edit_recipe_path(@recipe), class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      
      <div class="column is-3">
        
        <h2 style="text-align:center" >
          投稿者
          <br>
          <i class="fas fa-user" aria-hidden="true"></i> <%= @recipe.user.username %> さん
        </h2>
        <div class="card-content">
          <div class="card-image">
            <%= link_to user_path(@recipe.user), class: "panel-block" do %>
           　  <figure class="image", style="margin: auto;">
            　   <%= image_tag @recipe.user.image %>
              </figure>
            <% end %>
        </div>
        </div>
        <article class="panel is-light">
          <article class="media">
            <div class="media-content">
              <div class="content">
               <p class="panel-heading"><strong><%= @user.username %> </strong><br>
                  <%= form_for [@recipe, @comment] do |f| %>
                  <div>
                    <%= f.text_area :comment_content %>
                    <%= f.hidden_field :recipe_id, value: @recipe.id %>
                  </div><br>
                  <%= f.submit 'コメントする' %>
                  <% end %>
               </p>
             </div>
             <h2>コメント一覧</h2>
             <% @comments.each do |comment| %>
             <div>
             <%= comment.user.username %>：<%= comment.comment_content %>
             <hr>
             </div>
             <% end %>
             </article>
            </div>
          </article>
        </article>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
 <section class="hero is-dark is-small">
  <div class="hero-body">
    <div class="container">
      <h1 class="title is-size-6">
        プロフィール編集
      </h1>
    </div>
  </div>
</section>

<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
             <%= f.label :username,"ユーザー名", class: "label"%>
             <%= f.text_field :username, class: "input" %>
          </div>
          
          <div class="field">
             <%= f.label :email, "メールアドレス", class: "label" %>
             <%= f.text_field :email, class: "input" %>
          </div>
          
          <div class="field">
             <%= f.label :profile, "一言メッセージ", class: "label" %>
             <%= f.text_field :profile, maxlength: 30, class: "textarea" %>
          </div>
          
          <div class="field">
              <%= f.label :profile_image, "プロフィール画像", class: "label" %>
              <%= f.file_field :image %><br>
          </div>
          
          <%= f.submit "更新", class: "button is-success" %>
          
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-dark is-small">
  <div class="hero-body">
    <div class="container">
      <h1 class="title is-size-6">
        DONUT会員
      </h1>
    </div>
　</div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <% if user.image.attached? %>
                      <%= image_tag user.image %>
                    <% else %>
                      <%= image_tag "no-image.png" %>
                    <% end %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="title">
                <%=link_to user.username, user_path(user) %>
              </div>
              <div class="content">
                投稿数：<%= user.recipes.count %>
              </div>
            </div>
          </div> 
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
 <section class="hero is-dark is-small">
  <div class="hero-body">
    <div class="container">
      <h1 class="title is-size-6">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <% if @user.image.attached? %>
                <%= image_tag @user.image %>
              <% else %>
                <%= image_tag "no-image.png" %>
              <% end %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-5">
                    <strong><%= @user.username %></strong>
                </td>
                  <% if @user.id == current_user.id %>
                    <td>
                        <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                    </td>
                  <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.recipes.each do |recipe| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to recipe_path(recipe) do %>
                  <%#<%= attachment_image_tag recipe, :image, fallback: "no-image.png" %>
                  <% if recipe.photo.attached? %>
                    <%= image_tag recipe.photo %>
                  <% end %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to recipe_path(recipe), class: "panel-block" do %>
                    <span class="panel-icon">
                    </span>
                    コメント数: <%= recipe.comments.count %>
                  <% end %>
                  <%= link_to recipe_path(recipe), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    この投稿を見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_recipe_path(recipe), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      この投稿を編集する
                    <% end %>
                    <%= link_to recipe_path(recipe), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      この投稿を削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= recipe.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>